select C.TABLE_CATALOG, C.TABLE_SCHEMA, C.TABLE_NAME, C.COLUMN_NAME, C.ORDINAL_POSITION, C.COLUMN_DEFAULT,
         C.IS_NULLABLE, C.DATA_TYPE, C.CHARACTER_MAXIMUM_LENGTH, C.NUMERIC_PRECISION, 
         C.NUMERIC_SCALE, C.DATETIME_PRECISION
     from INFORMATION_SCHEMA.Columns as c 

Select c.TABLE_CATALOG, c.TABLE_SCHEMA, c.TABLE_NAME, c.COLUMN_NAME, t.TABLE_NAME as PkTable, t.COLUMN_NAME as PkColumnName,
      r.CONSTRAINT_CATALOG, r.CONSTRAINT_SCHEMA, r.CONSTRAINT_NAME, r.UNIQUE_CONSTRAINT_SCHEMA, r.UNIQUE_CONSTRAINT_NAME
   from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE as c
   Join INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS   as r
   on r.CONSTRAINT_CATALOG = c.CONSTRAINT_CATALOG
   and r.CONSTRAINT_SCHEMA = c.CONSTRAINT_SCHEMA
   and r.CONSTRAINT_NAME = c.CONSTRAINT_NAME
   Join INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE as t
   on t.CONSTRAINT_CATALOG = r.UNIQUE_CONSTRAINT_CATALOG
   and t.CONSTRAINT_SCHEMA = r.UNIQUE_CONSTRAINT_SCHEMA
   and t.CONSTRAINT_NAME = r.UNIQUE_CONSTRAINT_NAME

select tc.TABLE_SCHEMA, tc.TABLE_NAME, c.COLUMN_NAME,tc.CONSTRAINT_SCHEMA, tc.CONSTRAINT_NAME
   from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE as c
   join INFORMATION_SCHEMA.TABLE_CONSTRAINTS as tc
   on c.CONSTRAINT_SCHEMA = tc.CONSTRAINT_SCHEMA
   and c.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
   Where tc.CONSTRAINT_TYPE = 'PRIMARY KEY'

select * from INFORMATION_SCHEMA.SCHEMATA
