// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeFirstT4Example
{
    using System.Linq;
    using CodeFirst.Common;
    using KadGen.Common;
    using CodeFirstMetadataTest.PropertyChanged;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class PropertyChangedTemplate : CodeFirstT4CSharpBase<CodeFirstClass>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 10 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 
	OutputGenerationWarning();
    var classMeta = Meta as CodeFirstClass;
 
            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.ComponentModel;\r\n\r\n");
            
            #line 17 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 OutputNamespaceOpen(); 
            
            #line default
            #line hidden
            this.Write("\r\npublic class ");
            
            #line 19 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Meta.Name));
            
            #line default
            #line hidden
            this.Write(" : INotifyPropertyChanged\r\n\r\n");
            
            #line 21 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"

PushBracket();
foreach(var prop in Meta.Properties)
{ 
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldDeclaration(prop.Name, prop.PropertyType.Name)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 26 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\npublic event PropertyChangedEventHandler PropertyChanged;\r\n\r\nprotected virtual " +
                    "void OnPropertyChanged(string name)\r\n{\r\n    if (this.PropertyChanged != null)\r\n " +
                    "   {\r\n        this.PropertyChanged(this, new PropertyChangedEventArgs(name));\r\n " +
                    "   }\r\n}\r\n\r\n");
            
            #line 38 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"

foreach(var prop in Meta.Properties)
{
    OutputXmlComments(prop);
	OutputAttributes(prop);
    var fieldName = MakeFieldName(prop.Name);
    var propertyName = MakePublicName(prop.Name);
            
            #line default
            #line hidden
            
            #line 45 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropertyDeclaration(propertyName, prop.ScopeAccess, prop.PropertyType.Name)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 48 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 this.PushBracket(); 
            
            #line default
            #line hidden
            this.Write("  \r\n");
            
            #line 49 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 if (prop.CanGet) { 
            
            #line default
            #line hidden
            this.Write("get { return ");
            
            #line 50 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));
            
            #line default
            #line hidden
            this.Write("; }\r\n");
            
            #line 51 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 52 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 if (prop.CanGet) { 
            
            #line default
            #line hidden
            this.Write("set\r\n");
            
            #line 54 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 PushBracket(); 
            
            #line default
            #line hidden
            this.Write("\r\nif ( ");
            
            #line 56 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));
            
            #line default
            #line hidden
            this.Write(" != value )\r\n{ ");
            
            #line 57 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n   this.OnPropertyChanged(\"");
            
            #line 58 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("\");\r\n}\r\n");
            
            #line 60 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 PopBracket(); 
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 }
            
            #line default
            #line hidden
            
            #line 62 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 this.PopBracket();
} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 65 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\CodeFirstT4Example\PropertyChangedTemplate.tt"
 
PopBracket();
OutputNamespaceClose(); 

            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
