// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DomainGenerationTemplates
{
    using System.Linq;
    using CodeFirst.Common;
    using RoslynDom.Common;
    using CodeFirstMetadataTest.PropertyChanged;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class DemoPropertyChanged : CodeFirstT4CSharpBase<CodeFirstClass>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.ComponentModel;\r\n\r\nnamespace ");
            
            #line 10 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Meta.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n   public class ");
            
            #line 12 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Meta.Name));
            
            #line default
            #line hidden
            this.Write(" : INotifyPropertyChanged\r\n   {\r\n      public event PropertyChangedEventHandler P" +
                    "ropertyChanged;\r\n\r\n");
            
            #line 16 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
 foreach(var prop in Meta.Properties)
{   
   var fieldName = StringUtilities.CamelCase(prop.Name);
   var propertyName = StringUtilities.PascalCase(prop.Name);
 
            
            #line default
            #line hidden
            this.Write("      private ");
            
            #line 21 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyType.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));
            
            #line default
            #line hidden
            this.Write("\r\n      public ");
            
            #line 22 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.ScopeAccess));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 22 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyType.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 22 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));
            
            #line default
            #line hidden
            this.Write("\r\n      {\r\n         get { return ");
            
            #line 24 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));
            
            #line default
            #line hidden
            this.Write("; }\r\n         set { SetProperty(ref ");
            
            #line 25 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));
            
            #line default
            #line hidden
            this.Write(", value); }\r\n      }\r\n\r\n");
            
            #line 28 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"
 
} 
            
            #line default
            #line hidden
            this.Write("   }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 32 "C:\Users\Kathleen\Documents\Visual Studio 2013\Projects\CodeFirstMetadata\Examples\DomainGeneration\DomainGenerationTemplates\DemoPropertyChanged.tt"

public override string FilePathHint
{
   get
   { return @"{ExecutionPath}\..\..\..\DomainOutput\{MetadataFileName}2.g.cs";
   }
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
